### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by mud-ali** [matousposp08/APCompSciGame#1]
Hi

I am a very big fan of the great work being done for the community here. I would really appreciate if compiled binaries could be published under the Github `Releases` tab. I understand that this project is still a work in progress, but until then, I shall wait eagerly for a release date to be announced.

In the meantime, if you are looking for beta testers, I am willing to provide feedback and test out your game.

**Comment by Puhalenthi** [comment]
it will be posted very shortly (thursday period 7)
